# Библиотека numpy. Вычислительные задачи.

### Задание 1.
Создать numpy array с элементами от числа N до 0
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np

N = int(input('Ввести любое целое число: '))
vector_values = np.arange(N - 1, -1, -1) 
print(vector_values)

Ввести любое целое число: 10
[9 8 7 6 5 4 3 2 1 0]


### Задание 2.
Создать диагональную матрицу с элементами от N до 0. Посчитать сумму ее значений на диагонали.

In [5]:
import numpy as np

N = int(input('Ввести любое целое число: '))
vector_values = np.diag(np.arange(N - 1, -1, -1))
print(vector_values)
print(f'Сумма значений матрицы на диагонали: {vector_values.diagonal().sum()}')

Ввести любое целое число: 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений матрицы на диагонали: 45


### Задание 3.
Решите систему уравнений:
    
4x + 2y + z = 4
    
x + 3y = 12
    
5y + 4z = -3

In [6]:
from numpy import linalg

matrix = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
vector = np.array([4, 12, -3])

answers = linalg.solve(matrix, vector)

for i in answers:
    print(i)

0.4666666666666668
3.844444444444444
-5.555555555555555


### Задание 4. Из предлекционного материала.

In [8]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]
)


# На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])  

"""Найти самого похожего пользователя.
    Т.е. посчитать косинусное сходство между этим пользователем
    и всеми пользователями из массива user_stats.
"""
lst = []
for x in users_stats:
    a = np.linalg.norm(x)
    b = np.linalg.norm(next_user_stats)
    lst.append(np.dot(x, next_user_stats) / (a * b))
print(f'Номер посетителя, с максимально схожими покупками: {lst.index(max(lst))}')



Номер посетителя, с максимально схожими покупками: 7
